### ISSUE TITLE
Unused variable in the codelab text step 3

### ISSUE THREAD

**Issue by seagomezar** [googlecodelabs/maps-platform-101-js#5]
Hi, @amuramoto !!! I hope you are great!

I found some errors in the Codelab texts and code blocks here https://codelabs.developers.google.com/codelabs/maps-platform-101-js/index.html I will group here in this issue but let me know if you want me to raise separately.

1. Here: https://codelabs.developers.google.com/codelabs/maps-platform-101-js/index.html?index=..%2F..index#2
 in step 3, At the last block of code, there is an unused variable that got as a parameter in the function loadMapsJSAPI for no reason.
See attached image: 
<img width="771" alt="issue 1" src="https://user-images.githubusercontent.com/2058936/93403904-62fb5f00-f84e-11ea-80c7-82a983f0d5ac.png">

2. Here: https://codelabs.developers.google.com/codelabs/maps-platform-101-js/index.html?index=..%2F..index#5
 in step 6 at the 2 and very last block of code, there is a missed colon there, see attached:
<img width="757" alt="issue 2" src="https://user-images.githubusercontent.com/2058936/93403612-a0132180-f84d-11ea-8fb5-3bea8c8bd0f1.png">

3. Here: https://codelabs.developers.google.com/codelabs/maps-platform-101-js/index.html?index=..%2F..index#4
in step 5 at the run app function, the console.log disappeared and then it appears in the next steps.
<img width="770" alt="issue 3" src="https://user-images.githubusercontent.com/2058936/93403727-fa13e700-f84d-11ea-83a7-27ad42305183.png">

4. Here: https://codelabs.developers.google.com/codelabs/maps-platform-101-js/index.html?index=..%2F..index#5
At the clusterMarkers function, the markerCluster variable is unused, maybe we can clarify there is no reason for used here but if we can to change in further steps or other functions that reference is important!

I can help you to fix it if you give me access to the source of the codelab!

Cheers!

**Comment by AndriiMaliuta** [comment]
Hello @amuramoto,
Confirming what @seagomezar has written above: in [https://developers.google.com/codelabs/maps-platform/maps-platform-101-js#2](https://developers.google.com/codelabs/maps-platform/maps-platform-101-js#2) in the "**Your app.js file should look something like this**:" block of code the '**googleMapsAPIKey**' variable is defined as the parameter and as local variable and it gives the "**Module parse failed: Identifier 'googleMapsAPIKey' has already been declared**" error during compilation. Seems like this should be corrected.

**Comment by amuramoto** [comment]
Fixed! Thanks and apologies for the slow response on this.
