### ISSUE TITLE
Codelabs:Google Maps Platform—JavaScript

### ISSUE THREAD

**Issue by mspace-git** [googlecodelabs/maps-platform-101-js#6]
Hi,
There should be some minimum average time to complete any step that will be very useful to track a developer if its going with reading/understanding the content. if it's not happened then the steps color should not be change into blue which will help exactly to prevent false badge availability or its value. 

I Think, The above logic might be applicable for other Codelabs tutorials.

**Comment by amuramoto** [comment]
Thanks for flagging - fixed!
